---
- name: "Updating apt repo/cache"
  apt: update_cache=yes force_apt_get=yes cache_valid_time=3600
  become: true
  become_method: sudo

- name: "Installing Packages"
  package:
    name:
      - jq
      - bloodhound
      - nuclei
      - golang-go
      - pipx
    state: latest
  become: true
  become_method: sudo
