---
- name: Ensure pip3 is installed
  apt:
    name: python3-pip
    state: present
  become: true
  become_method: sudo

- name: Install Modules
  pip:
    name:
      - selenium
      - pyautogui
      - webdriver_manager
      - termcolor
      - cprint
      - pycryptodomex
      - requests
    executable: pip3